name: Publish extension

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Identify the release as a prerelease (default: false)'
        type: boolean
        default: false

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          node -p "require('./package.json').version"    
      - name: Install node packages
        run: |
          npm install
      - name: Install vsce tool
        run: |
          npm install -g vsce
      - name: Publish vsix package
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          option="$( ${{ github.event.inputs.prerelease == 'true' }} ? '--pre-release' : '')"
          vsce package ${option}
          vsce publish ${option} -i *.vsix
      - name: Upload vsix package
        uses: actions/upload-artifact@v3
        with:
          name: vscode-jy-test
          path: ./*.vsix
