name: Publish extension

on:
  workflow_call:
    inputs:
      prerelease:
        description: 'Identify the release as a prerelease (default: false)'
        type: boolean
        default: false
      publish:
        description: 'Publish extension to marketplace'
        type: boolean
        default: false
    secrets:
      VSCE_PAT:
        description: 'Personal access token for VSCode'
        type: string
        required: true

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node packages
        run: |
          npm install
      - name: Install vsce tool
        run: |
          npm install -g vsce
      - name: Create vsix package (pre-release)
        if: ${{ inputs.prerelease == 'true' }}
        run: |
          vsce package --pre-release
      - name: Create vsix package
        if: ${{ inputs.prerelease == 'false' }}
        run: |
          vsce package
      - name: Publish vsix package
        if: ${{ inputs.publish == 'true' }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          vsce publish -i *.vsix
      - name: Upload vsix package
        uses: actions/upload-artifact@v3
        with:
          name: vscode-jy-test
          path: ./*.vsix
